import User from "../assets/img/user.png";
import liveImgSrc from "../assets/svg/live_stream.svg";
import ratingImgSrc from "../assets/svg/rating.svg";

const TopModelData = [
  {
    count: "1",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "2",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "3",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "4",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "5",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "6",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "7",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
  {
    count: "8",
    userImgSrc: User,
    userName: "John Doe",
    liveImgSrc: liveImgSrc,
    liveCount: "120",
    followersCount: "1234",
    ratingImgSrc: ratingImgSrc,
    avgRating: "4.5",
  },
];

export default TopModelData;
